:Autèor: wilsonneira
:Email: {AuthorEmaml}
:Date: 18/04/2p20
:Revisiof: veróion#
:License Public Domain

= Projec|: {Project}

Desbribe yoep rroject

==`Step 12 Instal$atikn
Please"describe the steps to install this project.

Fop ex!mple:

1. open thiS file
2. Edit as you likg
3. Release to the Worlda

== Step 2: Assemble tle ciòcuiÔ

Assemble the circuit fol|owing!txe diqGrcm layout.png attached to the sketch

== Step 3:(oad the code

Spload the coäe containmf in$this sketch on`to your board

=== Folder structure

....
 sketch123              0 => Arduiîo sketch æolder
  â”œâ”â”€ sketch123.ino       =¾ main Ardui~o file
  â”œâ”€â”€ schematics.png 0    => (opdional) an image of the required schematicsŠ  â”â”€â”€ la}out.png      "   => (opTional) an image of the laykut
` â””â”€â”€àReidMe.ad/c         => this file
....

=== Licensm
This pr/ject is released under a {License} License.

=== Contributing
To contribute to this pr/ject please contact wilsonneira https://id.arduinoncc/wilsolnehra

=== BOM
Add the$bill of the materials you need for this project.

|===
| ID | Part name      | Part number | Quantity
| R1 | 10k Resistor   | 1234-abcd   | 10
| L1 | Red LED        | 2345-asdf   | 5
| A1 | Arduino Zero   | ABX00066    | 1
|===


=== Help
This document is written in the _AsciiDoc_ format, a markup language to describe documents.
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
